### ISSUE TITLE
extend getStatus to accept a preparedID

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject/ids.server#104]
In the new web frontend, it would be useful to display to users whether their historic downloads - identified by a preparedID - are still available to download: that is, to confirm that the Tidier has not deleted some of the files. As I understand it, the only way to do this at the moment would be to:
- call [getDataFileIDs](https://repo.icatproject.org/site/ids/server/1.10.1/miredot/index.html#-950935674) passing the preparedID as a parameter, receiving a list of Datafile IDs
- calling [getStatus](https://repo.icatproject.org/site/ids/server/1.10.1/miredot/index.html#-1347942225) on chunks of the Datafile IDs to confirm they are all online.

To avoid the round trip, it would be useful if getStatus accepted a preparedID. Obviously there is the [isPrepared](https://repo.icatproject.org/site/ids/server/1.10.1/miredot/index.html#-479488323) call, but that has the side-effect of requesting any missing data and we don't want that in this case.

Is this feasible? Would there be performance issues with this approach?

**Comment by stuartpullinger** [comment]
@agbeltran @louise-davies @Goelbiju may be interested to follow this issue.

**Comment by RKrahl** [comment]
For an authoritative answer I would need to have a look into the code.  But out of the gut I'd say this should be feasible and not really a problem.

**Comment by RKrahl** [comment]
There are more calls that operate on data, i.e. take `investigationIds`, `datasetIds`, and `datafileIds` as parameters, but not a `preparedId`: [archive()](https://repo.icatproject.org/site/ids/server/1.10.1/miredot/index.html#-1347000247), [delete()](https://repo.icatproject.org/site/ids/server/1.10.1/miredot/index.html#1300008592), [getSize()](https://repo.icatproject.org/site/ids/server/1.10.1/miredot/index.html#-402651970), [reset()](https://repo.icatproject.org/site/ids/server/1.10.1/miredot/index.html#1951642171), [restore()](https://repo.icatproject.org/site/ids/server/1.10.1/miredot/index.html#-2044223723), and [write()](https://repo.icatproject.org/site/ids/server/1.10.1/miredot/index.html#1209015910). While I assume that `archive()`, `delete()`, `reset()`, `restore()`, and `write()` are mostly relevant in admin scripts only and not in a user interface, so that there might not be the use case for them to take a `preparedId`, what about `getSize()`? I could imagine there is a use to query the size of the data corresponding to a `preparedId`. What do you think?

**Comment by stuartpullinger** [comment]
Yes, I think that is a good idea and shouldn't be too difficult to add at the same time. I will have a look at this when I get a chance but that might not be for a few weeks.

**Comment by RKrahl** [comment]
As expected, inspecting the sources shows that a simple implementation would be rather straightforward and easy to do.

On the other hand, the ids.server source is already awkward and desperately needs a major refactoring.  Unfortunately, the simple and straightforward implementation would lead to more code duplication and make the situation even worse. A smart implementation would require to refactor first.

So, depending how urgent you need this feature, I could either
- just do it quick and dirty,
- or defer it and do the refactoring first.  But this would take a significant amount of time.
