### ISSUE TITLE
Archive can be too slow

### ISSUE THREAD

**Issue by fisherab** [icatproject/ids.server#78]
With the current asynchronous archive process the disk can fill up

**Comment by RKrahl** [comment]
Do you have an idea what possibly could be done about this?

**Comment by fisherab** [comment]
I have dismissed the ideas I have had so far. I will try and think again before we meet next week

Steve

**Comment by fisherab** [comment]
Could call File.getFreeSpace in the plugin before beginning to write a file to main storage. If space is too low then wait a while. This should be fast and does not change any interfaces. If it takes too long then could check every nth call.

**Comment by RKrahl** [comment]
I need more info in order to do something about this. What is happening when this becomes an issue? Is it the main storage filling up too fast so that the Tidier is not able to keep up? If so, what is causing this fill up? Or is it the Tidier being just too slow? If so, what part in the Tidier is slow?

In fact, I would need a detailed description of the scenario, ideally including timings.

**Comment by RKrahl** [comment]
If nobody is able to deliver a detailed problem description, this may be taken as a hint that this is not that a serious problem.

**Comment by RKrahl** [comment]
No news since several months. Seems not to be relevant.
