### ISSUE TITLE
writeDelaySeconds configuration property is reused for deferring requests

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject/ids.server#94]
While debugging a timing issue, I have discovered that the writeDelaySeconds property in run.properties is also used to delay restore operations as [here](https://github.com/icatproject/ids.server/blob/master/src/main/java/org/icatproject/ids/FiniteStateMachine.java#L451).
 
I found [this](https://github.com/icatproject/ids.server/blob/master/src/main/java/org/icatproject/ids/FiniteStateMachine.java#L284) comment in [FiniteStateMachine.java](https://github.com/icatproject/ids.server/blob/master/src/main/java/org/icatproject/ids/FiniteStateMachine.java)
```Java
        /*
         * Note that the variable writeTime has been abused and now also delays
         * restore operations TODO
         */
```

I'm not sure yet whether the solution is to simply create a new configuration property or whether it is more complicated - there is a HashMap called writeTimes which is used in several places.

**Comment by stuartpullinger** [comment]
Yes, that's fine. I just wanted to make sure I noted it so I could come back to it another time. Adding the 1.10 Milestone.

**Comment by RKrahl** [comment]
A look into the sources reveals that in fact for storage unit `datafile`, all operations are delayed by `writeDelaySeconds`, not only `WRITE` and `RESTORE`, but also `ARCHIVE` and `DELETE`. This is not related to `writeTimes` because the latter is only used for storage unit `dataset`.

So the current behavior is:
- for storage unit `datafile`: if the first deferred operation is queued, wait `writeDelaySeconds` seconds and collect more deferred operations to come (regardless of the type). When the delay is elapsed, process them all at once, starting one thread per operation type. So we have one scalar `writeTime` (in the singular).
- for storage unit `dataset`: for each dataset individually, delay each `WRITE` operation by `writeDelaySeconds` seconds to see if more operations come in. A second `WRITE` operation for the same dataset pushes the delay further. It is eventually processed if no more `WRITE` operation have been queued for the same dataset within the delay. Other operation types and other datasets are not affected. So we have a Hashmap `writeTimes` (in the plural) with datasets as keys.

Besides the misleading property name, the behavior looks sensible to me.  It would probably be too expensive to start a new thread for each single deferred operation in the case of storage unit `datafile`. It makes sense to collect and combine them.

I would suggest two possible solutions:

1. Introduce two separate configuration properties, lets say `delayDatafileOperations` and `delayDatasetWrites` for the two cases above. The former would only be relevant if storage unit is set to `datafile`, the latter only if storage unit is `dataset`. The advantage would be a clearer distinction between the two cases.
2. Since only one configuration property is relevant for each case anyway, keep it with one single property. But rename it to something like `delayOperations` to avoid confusion and clearly document the slightly different semantic depending on the storage unit. The advantage would be to bloat the configuration file a little less with properties that might not be relevant.

Opinions? Preferences?

**Comment by RKrahl** [comment]
In the absence of feedback, I opted now for first solution, see #97.
