### ISSUE TITLE
Implement a 'Cancel PreparedId' API call

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject/ids.server#95]
This is referred to in icatproject/topcat#406 and has been discussed before in icatproject/topcat#152 and  icatproject/ids.server#41.

This API call would cancel the restoration of all the IDs associated with a given PreparedID. This was previously rejected because we wouldn't want to cancel restoration of files if another user had requested them. Well, that is true. But we wouldn't want to waste resources restoring files when we know that no-one wants them.

As far as I understand it, implementing this would be difficult as the IDS does not keep track of which PreparedId(s) a particular requested file belongs to - but I would like to consider it again as it seems that the current situation can easily lead to wasting of resources.

**Comment by RKrahl** [comment]
First of all, what you really seem to suggest, is rather a 'Cancel Restore' call. A `preparedId` is nothing than a record of a collection of dataset and datafile ids that is stored for later referral. Cancelling that is meaningless.

Cancelling the restore request is not trivial. Some unsorted notes:
- There is not one single restore request for all the items referenced by the preparedId. There are individual restore requests for each dataset or each datafile  (depending on the storage unit).
- Cancelling is in principle easy if the restore request is waiting in the queue of deferred operations, it just needs to be removed from there.
- Cancelling the restore may be disruptive if another user has also requested restoring some of the items. There is no way to see who else is waiting for the restore.
- If the restorer thread (`DfRestorer` or `DsRestorer`) has already been started, the ship has sailed. There is no way to stop the restore then.
- Depending on the configured storage unit, unless some other operation is blocking the restore, the operation may only wait for a short period of time in the queue. For storage unit dataset, the restorer will be started in the very next processing of the queue, e.g. the operation will wait at most `processQueueIntervalSeconds`, which is five seconds by default. For storage unit datafile, the request will be held back at most `writeDelaySeconds` which is 60 seconds by default.
- The 'cancel restore' call will not help in the case of the huge request involving 100,000 files that has recently been discussed on the list: in this case, it took 45 minutes just to check the status of the files. This check is done in a separate thread that loops over all files, checks if the file is online and submits a restore request if not. In this situation, the cancel will fail, because most of the restore requests will not yet be in the queue.

**Comment by stuartpullinger** [comment]
Thanks Rolf. Yes, you are correct: I mean an API call that would take a preparedId and cancel all the restores associated with it. And, yes, the IDS's implementation makes this difficult. Thanks for adding some issues I had not thought of!

**Comment by RKrahl** [comment]
As there is not really a way to properly do this and it has many unresolved issues, I close as wontfix.
